#! /usr/bin/env ruby
require 'strscan'
require_relative 'tokenize'
require_relative 'parse'
require_relative 'codegen'

if ARGV.length != 1
  error("#{ARGV.length}: invalid number of arguments")
end

# Tokenize and parse.
@user_input = ARGV[0]
@token = tokenize()
node = expr()

# Traverse the AST to emit assembly.
codegen(node)
